// <auto-generated />
namespace Formule1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Seconddriver : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seconddriver));
        
        string IMigrationMetadata.Id
        {
            get { return "201406020917013_Seconddriver"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
